// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/header.vue')['default']
    IFoundationPageDelete: typeof import('~icons/foundation/page-delete')['default']
    IFoundationPlus: typeof import('~icons/foundation/plus')['default']
    Todo: typeof import('./src/components/todo.vue')['default']
    TodoHead: typeof import('./src/components/todoHead.vue')['default']
    TodoWrapper: typeof import('./src/components/todoWrapper.vue')['default']
  }
}
